version: 2
jobs:
  build:
    working_directory: ~/ogp
    machine: true
    environment:
      DOCKER_URL: https://download.docker.com/linux/static/edge/x86_64/docker-17.05.0-ce.tgz
    steps:
      - checkout
      - run:
          name: Upgrade Docker
          command: |
            curl -sSL $DOCKER_URL | sudo tar -xz --strip-components=1 -C /usr/bin/
            sudo service docker restart
      - run:
          name: "Build Image"
          command: |
            make build
      - run:
          name: "Test"
          command: |
            docker-compose up -d web joshhsoj1902/docker-ogpweb:latest
            sleep 60
            docker ps
            docker exec dockerogpweb_web_1 "/docker-health.sh"
