version: '2'
services:
  web:
    image: joshhsoj1902/docker-ogpweb
    restart: always
    environment:
      - MYSQL_IP=my_db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASS=${DBPASS}
      - MYSQL_PREFIX=ogp_
    ports:
      - "80:80"
    volumes:
      - ./ogp_web/ogp/config:/var/www/html/includes/config
    links:
      - db:my_db
    depends_on:
      - db
  db:
    restart: always
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    #ports:
    #  - "3306:3306"
    volumes:
      - ./ogp_web/mysql/datadir:/var/lib/mysql
      #- ./ogp_web/mysql/config:/etc/mysql
