version: '2'
services:
  web:
    image: joshhsoj1902/docker-ogpweb:latest@sha256:53d5012ee0b1f860feefe91c47dc6fc9d0378dff7e0ea0d4f6e9d93893ab3057
    restart: always
    environment:
      - OGP_INSTALL=true
      - MYSQL_IP=my_db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=opengamepanel
      - MYSQL_USER=ogpuser
      - MYSQL_PASS=foo
      - MYSQL_PREFIX=ogp_
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=adminadmin
      - ADMIN_EMAIL=admin@email.com
    ports:
      - "10001:80"
    links:
      - db:my_db
    depends_on:
      - db
  db:
    restart: always
    image: mysql:5.6@sha256:16eefe638c159c5e94d04d031cce5afae0bb873bb145f2343c36d26ff80ab275
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=opengamepanel
      - MYSQL_USER=ogpuser
      - MYSQL_PASSWORD=foo
    volumes:
      - /var/lib/mysql
  # agent:
  #   restart: always
  #   image: joshhsoj1902/docker-ogpagent-docker
  #   ports:
  #    - "12679:12679"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - OGP_LISTEN_PORT=12679
  #     - OGP_KEY=encryption_key2
  #     - OGP_DOCKER_NAMESPACE=joshhsoj1902
