FROM ubuntu:16.04

MAINTAINER joshhsoj1902 

RUN apt-get update
RUN apt-get install -y mysql-server php5 php5-gd php5-xmlrpc php5-curl php5-mysql php-pear curl apache2 

RUN svn co svn://svn.code.sf.net/p/hldstart/svn/trunk/upload/ ~/public_html/ogp 

EXPOSE 80

CMD /usr/sbin/apache2ctl -D FOREGROUND
