defaults: &defaults 
    working_directory: ~/build
    docker: 
      - image: joshhsoj1902/circleci-build-image:1.0.8@sha256:87c9fcce5f5474f34407f12640fd89903070e4de467724294e687a4442d2fe0c
remote_docker_version: &remote_docker_version
    version: 17.11.0-ce
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          <<: *remote_docker_version
      - run:
          name: Pull public docker images in the background
          background: true
          command: |
             docker-compose pull db
      - run:
          name: "Build Image"
          command: |
            make build
      - run:
          name: "Test"
          command: |
            docker-compose up -d web
            sleep 60
            docker ps
            docker-compose logs web
            docker-compose exec web "/docker-health.sh"
            docker-compose exec web "/was-installer-removed.sh"
            